spring.application.name=sms
spring.datasource.url=jdbc:mysql://localhost:3306/sms

spring.datasource.username=root
spring.datasource.password=_Janaki75

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true